(cl:in-package pmdCam-msg)
(cl:export '(IFM_TIME-VAL
          IFM_TIME
          MODULATION_FREQUENCY-VAL
          MODULATION_FREQUENCY
          ILLU_MODE-VAL
          ILLU_MODE
          RESET_DURATION-VAL
          RESET_DURATION
          MEDIAN_FILTER-VAL
          MEDIAN_FILTER
          MEAN_FILTER-VAL
          MEAN_FILTER
          TRIGGER_MODE-VAL
          TRIGGER_MODE
          SAMPLING_MODE-VAL
          SAMPLING_MODE
          INTEGRATION_TIME_SINGLE-VAL
          INTEGRATION_TIME_SINGLE
          INTEGRATION_TIME_DOUBLE-VAL
          INTEGRATION_TIME_DOUBLE
          DELAY_TIME-VAL
          DELAY_TIME
          UNAMBIGUOUS_RANGE-VAL
          UNAMBIGUOUS_RANGE
          EVALUATION_TIME-VAL
          EVALUATION_TIME
          DATA_PORT-VAL
          DATA_PORT
          IP-VAL
          IP
          XML_PORT-VAL
          XML_PORT
))