"""autogenerated by genmsg_py from image_box.msg. Do not edit."""
import roslib.message
import struct

import std_msgs.msg
import sensor_msgs.msg

class image_box(roslib.message.Message):
  _md5sum = "fbd3b500ad7f213eb88fab1e3233d49f"
  _type = "pmdCam/image_box"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """sensor_msgs/Image img1
sensor_msgs/Image img2
sensor_msgs/Image img3
sensor_msgs/Image img4

================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of cameara
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in src/image_encodings.cpp

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['img1','img2','img3','img4']
  _slot_types = ['sensor_msgs/Image','sensor_msgs/Image','sensor_msgs/Image','sensor_msgs/Image']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       img1,img2,img3,img4
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(image_box, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.img1 is None:
        self.img1 = sensor_msgs.msg.Image()
      if self.img2 is None:
        self.img2 = sensor_msgs.msg.Image()
      if self.img3 is None:
        self.img3 = sensor_msgs.msg.Image()
      if self.img4 is None:
        self.img4 = sensor_msgs.msg.Image()
    else:
      self.img1 = sensor_msgs.msg.Image()
      self.img2 = sensor_msgs.msg.Image()
      self.img3 = sensor_msgs.msg.Image()
      self.img4 = sensor_msgs.msg.Image()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.img1.header.seq, _x.img1.header.stamp.secs, _x.img1.header.stamp.nsecs))
      _x = self.img1.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.img1.height, _x.img1.width))
      _x = self.img1.encoding
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.img1.is_bigendian, _x.img1.step))
      _x = self.img1.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.img2.header.seq, _x.img2.header.stamp.secs, _x.img2.header.stamp.nsecs))
      _x = self.img2.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.img2.height, _x.img2.width))
      _x = self.img2.encoding
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.img2.is_bigendian, _x.img2.step))
      _x = self.img2.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.img3.header.seq, _x.img3.header.stamp.secs, _x.img3.header.stamp.nsecs))
      _x = self.img3.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.img3.height, _x.img3.width))
      _x = self.img3.encoding
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.img3.is_bigendian, _x.img3.step))
      _x = self.img3.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.img4.header.seq, _x.img4.header.stamp.secs, _x.img4.header.stamp.nsecs))
      _x = self.img4.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.img4.height, _x.img4.width))
      _x = self.img4.encoding
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.img4.is_bigendian, _x.img4.step))
      _x = self.img4.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.img1 is None:
        self.img1 = sensor_msgs.msg.Image()
      if self.img2 is None:
        self.img2 = sensor_msgs.msg.Image()
      if self.img3 is None:
        self.img3 = sensor_msgs.msg.Image()
      if self.img4 is None:
        self.img4 = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.img1.header.seq, _x.img1.header.stamp.secs, _x.img1.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img1.height, _x.img1.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img1.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img1.is_bigendian, _x.img1.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img1.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img2.header.seq, _x.img2.header.stamp.secs, _x.img2.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img2.height, _x.img2.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img2.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img2.is_bigendian, _x.img2.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img2.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img3.header.seq, _x.img3.header.stamp.secs, _x.img3.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img3.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img3.height, _x.img3.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img3.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img3.is_bigendian, _x.img3.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img3.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img4.header.seq, _x.img4.header.stamp.secs, _x.img4.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img4.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img4.height, _x.img4.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img4.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img4.is_bigendian, _x.img4.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img4.data = str[start:end]
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.img1.header.seq, _x.img1.header.stamp.secs, _x.img1.header.stamp.nsecs))
      _x = self.img1.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.img1.height, _x.img1.width))
      _x = self.img1.encoding
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.img1.is_bigendian, _x.img1.step))
      _x = self.img1.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.img2.header.seq, _x.img2.header.stamp.secs, _x.img2.header.stamp.nsecs))
      _x = self.img2.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.img2.height, _x.img2.width))
      _x = self.img2.encoding
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.img2.is_bigendian, _x.img2.step))
      _x = self.img2.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.img3.header.seq, _x.img3.header.stamp.secs, _x.img3.header.stamp.nsecs))
      _x = self.img3.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.img3.height, _x.img3.width))
      _x = self.img3.encoding
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.img3.is_bigendian, _x.img3.step))
      _x = self.img3.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.img4.header.seq, _x.img4.header.stamp.secs, _x.img4.header.stamp.nsecs))
      _x = self.img4.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.img4.height, _x.img4.width))
      _x = self.img4.encoding
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.img4.is_bigendian, _x.img4.step))
      _x = self.img4.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.img1 is None:
        self.img1 = sensor_msgs.msg.Image()
      if self.img2 is None:
        self.img2 = sensor_msgs.msg.Image()
      if self.img3 is None:
        self.img3 = sensor_msgs.msg.Image()
      if self.img4 is None:
        self.img4 = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.img1.header.seq, _x.img1.header.stamp.secs, _x.img1.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img1.height, _x.img1.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img1.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img1.is_bigendian, _x.img1.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img1.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img2.header.seq, _x.img2.header.stamp.secs, _x.img2.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img2.height, _x.img2.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img2.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img2.is_bigendian, _x.img2.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img2.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img3.header.seq, _x.img3.header.stamp.secs, _x.img3.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img3.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img3.height, _x.img3.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img3.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img3.is_bigendian, _x.img3.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img3.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.img4.header.seq, _x.img4.header.stamp.secs, _x.img4.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img4.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.img4.height, _x.img4.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img4.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.img4.is_bigendian, _x.img4.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.img4.data = str[start:end]
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_3I = struct.Struct("<3I")
_struct_2I = struct.Struct("<2I")
_struct_BI = struct.Struct("<BI")
